### ISSUE TITLE
Create a pre-launch checklist

### ISSUE THREAD

**Issue by lillianjwarner** [halfaker-and-associates/vsa-itd#22]
<H1>Pre-launch Checklist</H1>

## Problem Statement: 

[Write problem statement: "How might we..."]

## Definition of Done: 

Is the product...

### Usable?

- [ ] Staging/dev QA complete
- [ ] 508 audit complete and launch-necessary updates complete
- [ ] e2e manual testing complete and bugs fixed
- [ ] User Acceptance Testing complete and successful

### Discoverable?

- [ ] URL and nav are ready
- [ ] SEO is set up
- [ ] Any necessary redirects/crosslinks from other webpages are in place
- [ ] Supporting static content is ready

### Secure?

- [ ] Security experts have reviewed

### Reliable?

- [ ] Alerts configured (saturation, error rate, latency, availability)
- [ ] Rate limits set
- [ ] Downtime notification rules and messaging set

### Trackable?

- [ ] Analytics set up
- [ ] Monitoring set up
- [ ] Logging configured

### Live?
- [ ] Go/no-go complete and successful
- [ ] Product launched
